#ifndef CONFIGURATION_H
#define CONFIGURATION_H

// BOARD CONFIGS
#define BOARD_TYPE PICO

// COMMUNICATION CONFIGS
#define MASTER_UART_ID uart1
#define MASTER_UART_BAUD_RATE 115200

#define MASTER_UART_TX_PIN 4
#define MASTER_UART_RX_PIN 5

// CONTROL CONFIGS
#define TIME_STEP 10

#define THRUST_P 1
#define THRUST_I 0
#define THRUST_D 0
#define THRUST_MAX 100
#define THRUST_MIN -100

#define STEERING_P 1
#define STEERING_I 0
#define STEERING_D 0
#define STEERING_MAX 100
#define STEERING_MIN -100

#define THRUST_PWM_PERIOD_US 4

#endif // CONFIGURATION_H